[[rules]]
name = "send_stmt"
query = """
(
    (send_statement) @send_stmt
)
"""

[[rules]]
name = "func_lit"
query = """
(
    (func_literal) @func_lit
)
"""

[[rules]]
name = "method_decl"
query = """
(
    (method_declaration) @method_decl
)
"""

[[rules]]
name = "return_stmt"
query = """
(
    (return_statement) @return_stmt
)
"""

[[rules]]
name = "make_chan"
query = """
(
    (short_var_declaration
        left:  (expression_list
            (identifier) @chan_id
        )
        right: (expression_list
            (call_expression
                function: (identifier) @func_id
                arguments: (
                    argument_list (
                        (channel_type) @chan_type
                    )
                )
            )
        )
    )
    (#eq? @func_id "make")
)
"""
