name: JS Format
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: javascript

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: '.github/filters.yaml'
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Format
        if: ${{ steps.filter.outputs.js == 'true' }}
        run: |
          npm ci
          npm run check_format
