name: JS Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    env: 
        HUSKY_SKIP_INSTALL: 1
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: '.github/filters.yaml'
      - uses: hallee/eslint-action@1.0.3
        # always running when it's a push
        # otherwise, only when modifications in js's dir
        if: ${{ github.event_name == 'push' || steps.filter.outputs.js == 'true' }}
        with:
          # GITHUB_TOKEN in forked repositories is read-only
          # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
          repo-token: ${{secrets.GITHUB_TOKEN}}
          source-root: javascript
