# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: javascript

jobs:
  # runs change detection
  # this job allows build to have a single if
  changes:
    runs-on: ubuntu-latest
    outputs:
      js: ${{ steps.filter.outputs.js }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            js:
              - javascript/**

  build:
    runs-on: ubuntu-latest
    needs: changes
    # always running when it's a push
    # otherwise, only when modifications in js's dir
    if: ${{ github.event_name == 'push' || needs.changes.outputs.js == 'true' }}
    
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -  run: npm ci
      -  run: npm test
      -  run: npm test
